import { GraphTraceResult, Section94NoticeData } from "../types";

export class BnssNoticeGenerator {
  /**
   * Compiles formal Section 94 BNSS Police Freezing Order data from a completed graph trace
   */
  static generateSection94Notice(
    trace: GraphTraceResult,
    officerInfo?: Partial<Section94NoticeData["investigatingOfficer"]>,
    complaintInfo?: Partial<Section94NoticeData["complaintDetails"]>
  ): Section94NoticeData {
    const vasp = trace.destinationVasp || {
      name: "Binance",
      depositAddress: trace.nodes[trace.nodes.length - 2]?.fullAddress || "0x...",
      vaultAddress: trace.nodes[trace.nodes.length - 1]?.fullAddress || "0x...",
      fiuRegistered: true,
      fiuNumber: "FIU-IND/RE/2024/0089",
      complianceEmail: "compliance-india@binance.com",
      detectedAt: trace.generatedAtUtc,
      confidenceScore: 98.5,
    };

    const noticeNumber = `CYBER/CY-PS/SEC94-BNSS/${new Date().getFullYear()}/${Math.floor(100000 + Math.random() * 900000)}`;

    return {
      noticeId: noticeNumber,
      date: new Date().toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "long",
        year: "numeric",
      }),
      investigatingOfficer: {
        name: officerInfo?.name || "Inspector Vikramaditya Rathore",
        designation: officerInfo?.designation || "Cyber Crime Police Station",
        policeStation: officerInfo?.policeStation || "Cyber Crime Police Station, MHA / I4C Nodal Cell",
        district: officerInfo?.district || "New Delhi Cyber Zone",
        state: officerInfo?.state || "Delhi NCT",
        contactEmail: officerInfo?.contactEmail || "investigations@cybercrime.gov.in",
        contactPhone: officerInfo?.contactPhone || "+91-11-2309-1930",
      },
      complaintDetails: {
        ackNumber1930: complaintInfo?.ackNumber1930 || "1930/CFCFRMS/2026/091248",
        crimeDate: complaintInfo?.crimeDate || new Date().toISOString().split("T")[0],
        victimName: complaintInfo?.victimName || "Rajesh Kumar Sharma",
        stolenAmountInr: complaintInfo?.stolenAmountInr || 1000000,
        stolenAmountUsdt: complaintInfo?.stolenAmountUsdt || trace.totalVolumeTrackedUsd,
        sourceBankOrAccount: complaintInfo?.sourceBankOrAccount || "State Bank of India (A/C: ****4921)",
        suspectInitialAddress: trace.rootAddress,
      },
      vaspRecipient: {
        name: vasp.name,
        fiuNumber: vasp.fiuNumber,
        legalEntityName: vasp.name === "Binance" ? "Nest Services Limited / Binance Holdings" : `${vasp.name} Financial Technologies Ltd`,
        complianceEmail: vasp.complianceEmail,
        nodalOfficerName: "Nodal Officer / Legal Compliance Desk",
      },
      forensicTrail: {
        depositAddress: vasp.depositAddress,
        depositTxHash: trace.edges[trace.edges.length - 1]?.txHash || "0x...",
        depositAmountUsdt: trace.totalVolumeTrackedUsd,
        depositTimestampUtc: vasp.detectedAt,
        vaultSweptTo: vasp.vaultAddress,
        hopPath: trace.nodes.map((n) => `${n.label} [${n.fullAddress.slice(0, 8)}...]`),
      },
      statutoryDirectives: [
        `IMMEDIATE FREEZE: In exercise of powers conferred under Section 94 of Bharatiya Nagarik Suraksha Sanhita (BNSS, 2023), you are hereby directed to IMMEDIATELY LOCK, FREEZE, AND SUSPEND all withdrawal, trading, P2P, and transfer privileges on the user account associated with deposit address ${vasp.depositAddress}.`,
        `FULL KYC & IP DISCLOSURE: Furnish certified true copies of all Know-Your-Customer (KYC) documentation (Aadhaar/PAN/Passport, selfie verification, phone number, email) and access audit logs (login IPs, device fingerprints, linked bank accounts) within 24 hours of receipt.`,
        `CHAIN-OF-CUSTODY PRESERVATION: Maintain cryptographic hash logs of all digital assets currently in lien and refrain from disclosing this statutory notice to the account holder pursuant to BNSS provisions.`,
      ],
      cryptographicVerification: {
        sha256Hash: trace.sha256StateHash,
        extractionBlockNumber: 21948201,
        bsaSection63Clause: "This digital record is generated by AEGIS-TRACE pursuant to Section 63 of Bharatiya Sakshya Adhiniyam (BSA, 2023) from immutable public distributed ledgers and constitutes admissible electronic evidence without manual tampering.",
      },
    };
  }
}
